version: '3.1'
networks:
  default:
    driver: 'bridge'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    environment:
      - PORT=4000
    networks:
      default:
    restart: always
    ports:
      - '4000:4000'
